version: '3.8'

services:
  vue:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '5173:5173'
    command: npm run dev -- --host
